### ISSUE TITLE
Prevent tasks from running on Pull Request builds

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.Recipe#800]
Some tasks are executed during a Pull Request build, when they shouldn't be.

For example, pushing packages to NuGet/Chocolatey feeds shouldn't happen when running on a PR build.  The packages should be created, but they shouldn't be published anywhere.

**Comment by gep13** [comment]
The logic for identifying a PR is:

```
var headRef = context.BuildSystem().GitHubActions.Environment.Workflow.HeadRef;
        var branchRef = context.BuildSystem().GitHubActions.Environment.Workflow.Ref;

        IsPullRequest = !string.IsNullOrEmpty(headRef) && !string.IsNullOrEmpty(branchRef)
            && branchRef.IndexOf("refs/pull/") >= 0 && branchRef.IndexOf("/merge") >= 0;
```

However, in an example PR, the following values are in play:

```
               CI: true
             HOME: [NULL]
       GITHUB_REF: 
refs/heads/dependabot/nuget/develop/Microsoft.NET.Test.Sdk-16.9.1
       GITHUB_SHA: 861277b8e81f200042b5d9a358f5e74833c85d97
     GITHUB_ACTOR: dependabot[bot]
    GITHUB_ACTION: cake-buildcake-action
    GITHUB_RUN_ID: 604078695
   GITHUB_ACTIONS: true
  GITHUB_BASE_REF: 
  GITHUB_HEAD_REF: 
  GITHUB_WORKFLOW: Build
 GITHUB_WORKSPACE: D:\a\Cake.Json\Cake.Json
GITHUB_EVENT_NAME: push
GITHUB_EVENT_PATH: D:\a\_temp\_github_workflow\event.json
GITHUB_REPOSITORY: ***/Cake.Json
GITHUB_RUN_NUMBER: 15
```
