### ISSUE TITLE
remove conditional builds from GitHub documentation

### ISSUE THREAD

**Issue by nils-a** [cake-contrib/Cake.Recipe#809]
GitHub Actions documentations still shows 

```yaml
# ...
build:
    runs-on: ${{ matrix.os }}
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
# ...
```

Since we established that this `if` effectively stops Cake.Recipe from performing it's magic on PRs that originate in the same repository (e.g. dependabot-PRs) this line (and it's explaining section) should be removed and the push triggers set to 

```yaml
  push:
    branches:
      - main
      - develop
      - "feature/**"
      - "release/**"
      - "hotfix/**"
    tags:
      - "*"
```
